name: Build Rider & Driver APKs (Flutter)

on:
  workflow_dispatch:
    inputs:
      vps_host:
        description: VPS host
        required: false
        default: 159.198.36.105
      vps_user:
        description: VPS user
        required: false
        default: root
      android_maps_key:
        description: Optional Google Maps key; leave blank to use secret
        required: false

jobs:
  build:
    name: Build debug APKs
    runs-on: ubuntu-latest
    env:
      VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      ANDROID_MAPS_FALLBACK: ${{ secrets.ANDROID_MAPS_DEV_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Java setup with Gradle cache is performed after rsync

      - name: Set up Flutter 3.24.3 (Dart 3.5.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Install rsync and sshpass
        run: sudo apt-get update && sudo apt-get install -y rsync sshpass

      - name: Add VPS host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ github.event.inputs.vps_host || '159.198.36.105' }}" >> ~/.ssh/known_hosts

      - name: Sync Rider from VPS
        run: |
          mkdir -p rider
          SSHPASS="$VPS_PASSWORD" rsync -a --delete \
            -e "sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no" \
            "${{ github.event.inputs.vps_user || 'root' }}@${{ github.event.inputs.vps_host || '159.198.36.105' }}:/var/www/tagxi/appsrc/Main-File-August-20/flutter_user/flutter_user/" \
            rider/

      - name: Sync Driver from VPS
        run: |
          mkdir -p driver
          SSHPASS="$VPS_PASSWORD" rsync -a --delete \
            -e "sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no" \
            "${{ github.event.inputs.vps_user || 'root' }}@${{ github.event.inputs.vps_host || '159.198.36.105' }}:/var/www/tagxi/appsrc/Main-File-August-20/flutter_driver/flutter_driver/" \
            driver/

      - name: Set up Java 17 (enable Gradle cache after sync)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            rider/android/**/gradle-wrapper.properties
            rider/android/**/*.gradle*
            driver/android/**/gradle-wrapper.properties
            driver/android/**/*.gradle*

      - name: Enforce dependency pins (Rider)
        working-directory: rider
        run: |
          set -e
          if ! grep -q '^dependency_overrides:' pubspec.yaml; then
            printf "\ndependency_overrides:\n  collection: 1.18.0\n" >> pubspec.yaml
          else
            # Remove any existing 'collection:' within the dependency_overrides block
            sed -i '/^dependency_overrides:/,/^[^[:space:]]/{/^[[:space:]]*collection:[[:space:]]*/d}' pubspec.yaml
            # Append the pinned collection version just after dependency_overrides
            sed -i '/^dependency_overrides:/a\  collection: 1.18.0' pubspec.yaml
          fi

      - name: Enforce dependency pins (Driver)
        working-directory: driver
        run: |
          set -e
          if ! grep -q '^dependency_overrides:' pubspec.yaml; then
            printf "\ndependency_overrides:\n  collection: 1.18.0\n" >> pubspec.yaml
          else
            # Remove any existing 'collection:' within the dependency_overrides block
            sed -i '/^dependency_overrides:/,/^[^[:space:]]/{/^[[:space:]]*collection:[[:space:]]*/d}' pubspec.yaml
            # Append the pinned collection version just after dependency_overrides
            sed -i '/^dependency_overrides:/a\  collection: 1.18.0' pubspec.yaml
          fi
          sed -i 's/^\(\s*location:\s*\).*/\1^7.0.0/' pubspec.yaml || true
          sed -i 's/^\(\s*flutter_map:\s*\).*/\1^7.0.0/' pubspec.yaml || true

      - name: Copy google-services.json if available
        run: |
          set -e
          if [ -f deploy/outputs/firebase_configs/google-services-com.hayyaride.rider.json ]; then
            mkdir -p rider/android/app
            cp -f deploy/outputs/firebase_configs/google-services-com.hayyaride.rider.json rider/android/app/google-services.json || true
          fi
          if [ -f deploy/outputs/firebase_configs/google-services-com.hayyaride.driver.json ]; then
            mkdir -p driver/android/app
            cp -f deploy/outputs/firebase_configs/google-services-com.hayyaride.driver.json driver/android/app/google-services.json || true
          fi

      - name: Create stub google-services.json if missing (Rider)
        run: |
          set -e
          if [ ! -f rider/android/app/google-services.json ]; then
            mkdir -p rider/android/app
            printf '{"project_info":{"project_id":"stub"},"client":[{"client_info":{"mobilesdk_app_id":"1:123:android:stub","android_client_info":{"package_name":"com.hayyaride.rider"}}}],"configuration_version":"1"}' > rider/android/app/google-services.json
          fi

      - name: Create stub google-services.json if missing (Driver)
        run: |
          set -e
          if [ ! -f driver/android/app/google-services.json ]; then
            mkdir -p driver/android/app
            printf '{"project_info":{"project_id":"stub"},"client":[{"client_info":{"mobilesdk_app_id":"1:123:android:stub","android_client_info":{"package_name":"com.hayyaride.driver"}}}],"configuration_version":"1"}' > driver/android/app/google-services.json
          fi

      - name: Inject Google Maps key (Rider)
        run: |
          set -e
          mkdir -p rider/android/app/src/main/res/values
          KEY="${{ github.event.inputs.android_maps_key }}"
          if [ -z "$KEY" ]; then KEY="$ANDROID_MAPS_FALLBACK"; fi
          printf '<resources>\n  <string name="google_maps_key" templateMergeStrategy="replace" translatable="false">%s</string>\n</resources>\n' "$KEY" > rider/android/app/src/main/res/values/google_maps_api.xml

      - name: Inject Google Maps key (Driver)
        run: |
          set -e
          mkdir -p driver/android/app/src/main/res/values
          KEY="${{ github.event.inputs.android_maps_key }}"
          if [ -z "$KEY" ]; then KEY="$ANDROID_MAPS_FALLBACK"; fi
          printf '<resources>\n  <string name="google_maps_key" templateMergeStrategy="replace" translatable="false">%s</string>\n</resources>\n' "$KEY" > driver/android/app/src/main/res/values/google_maps_api.xml

      - name: flutter pub get (Rider)
        working-directory: rider
        run: |
          set -e
          flutter pub get || (flutter pub add --dev flutter_lints:^4.0.0 && flutter pub get)

      - name: flutter pub get (Driver)
        working-directory: driver
        run: |
          set -e
          flutter pub get || (flutter pub add --dev flutter_lints:^4.0.0 && flutter pub get)

      - name: Build Rider debug APK
        working-directory: rider
        run: flutter build apk --debug

      - name: Build Driver debug APK
        working-directory: driver
        run: flutter build apk --debug

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: hayyaride-apks
          path: |
            rider/build/app/outputs/flutter-apk/app-debug.apk
            driver/build/app/outputs/flutter-apk/app-debug.apk

      - name: Create PR with pinned dependencies
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/pin-deps-dart-3-5-3
          delete-branch: true
          commit-message: "Pin dependencies for Dart 3.5.3 compatibility (Driver: location/flutter_map; both: collection override)"
          title: "Pin Rider & Driver dependencies for Flutter 3.24.3 / Dart 3.5.3"
          body: |
            This PR persists the dependency pins applied during CI so future builds don't rely on CI-time edits.

            - Pin Driver `location:^7.0.0` and `flutter_map:^7.0.0` to avoid Dart >=3.6 constraints.
            - Add `dependency_overrides: collection: 1.18.0` to both Rider and Driver.
            - These pins ensure `flutter pub get` succeeds on Flutter 3.24.3 (Dart 3.5.3).
            - Revert by removing the override and upgrading to `location`/`flutter_map` ^8 when moving to Dart/Dart SDK >= 3.6.
          add-paths: |
            rider/pubspec.yaml
            driver/pubspec.yaml
