name: Build Rider & Driver APKs (Flutter)

on:
  workflow_dispatch:
    inputs:
      vps_host:
        description: "VPS host"
        required: true
        default: "159.198.36.105"
      vps_user:
        description: "VPS user"
        required: true
        default: "root"
      app_rider_path:
        description: "Absolute path to rider Flutter app on VPS"
        required: true
        default: "/var/www/tagxi/appsrc/Main-File-August-20/flutter_user/flutter_user"
      app_driver_path:
        description: "Absolute path to driver Flutter app on VPS"
        required: true
        default: "/var/www/tagxi/appsrc/Main-File-August-20/flutter_driver/flutter_driver"
      android_maps_key:
        description: "Android Maps API key (dev) - optional if secret provided"
        required: false

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine available secrets
        id: secrets
        run: |
          echo "has_vps=${{ secrets.VPS_PASSWORD != '' }}" >> "$GITHUB_OUTPUT"
          echo "has_gcp=${{ secrets.GCP_SA_KEY_JSON != '' }}" >> "$GITHUB_OUTPUT"

      - name: Install tooling (sshpass, rsync)
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client sshpass jq

      - name: Add VPS host to known_hosts
        if: ${{ steps.secrets.outputs.has_vps == 'true' }}
        env:
          VPS_HOST: ${{ github.event.inputs.vps_host || '159.198.36.105' }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 "$VPS_HOST" >> ~/.ssh/known_hosts

      - name: Rsync Rider and Driver projects from VPS
        if: ${{ steps.secrets.outputs.has_vps == 'true' }}
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
        run: |
          set -e
          VPS_HOST="${{ github.event.inputs.vps_host }}"
          VPS_USER="${{ github.event.inputs.vps_user }}"
          RIDER_PATH="${{ github.event.inputs.app_rider_path }}"
          DRIVER_PATH="${{ github.event.inputs.app_driver_path }}"
          echo "Syncing from ${VPS_USER}@${VPS_HOST}"
          sshpass -e rsync -a --delete "${VPS_USER}@${VPS_HOST}:${RIDER_PATH}/" ./rider/
          sshpass -e rsync -a --delete "${VPS_USER}@${VPS_HOST}:${DRIVER_PATH}/" ./driver/

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"
          cache: true

      - name: Flutter version
        run: |
          flutter --version
          dart --version

      - name: Flutter pub get (Rider)
        working-directory: rider
        run: |
          flutter clean
          flutter pub get

      - name: Flutter pub get (Driver)
        working-directory: driver
        run: |
          flutter clean
          flutter pub get

      - name: Build Rider APK (debug)
        working-directory: rider
        run: flutter build apk --debug

      - name: Build Driver APK (debug)
        working-directory: driver
        run: flutter build apk --debug

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hayyaride-apks
          path: |
            rider/build/app/outputs/flutter-apk/app-debug.apk
            driver/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: ignore
